import {test} from 'node:test';import assert from 'node:assert/strict';import worker,{imageType} from './worker.js';
const origin='https://novahomeconstruction.ca';
function database(){const rows=new Map();let n=0;return {prepare(sql){let args;return {bind(...a){args=a;return this},async first(){if(sql.includes('RETURNING'))return {n:++n};return rows.get(args[0])},async run(){if(sql.startsWith('INSERT OR IGNORE')&&!rows.has(args[0]))rows.set(args[0],{hash:args[1],created:args[2],sent:0});if(sql.startsWith('UPDATE requests'))rows.get(args[0]).sent=1;return {}}}}}}
function setup(){return {DB:database(),ALLOWED_ORIGINS:origin,ALLOWED_HOSTNAMES:'novahomeconstruction.ca',RESEND_API_KEY:'test',TURNSTILE_SECRET:'test',RATE_SECRET:'test',FROM_EMAIL:'NOVA <test@example.com>'}}
function req(overrides={},photo){const f=new FormData();for(const [k,v] of Object.entries({name:'Test Person',email:'test@example.com',phone:'8252884475',service:'Kitchen Renovation',description:'Test kitchen project',requestId:'12345678-1234-1234-1234-123456789abc',token:'test',...overrides}))f.set(k,v);if(photo)f.append('photos',photo,'test.png');return new Request(origin,{method:'POST',headers:{Origin:origin,'CF-Connecting-IP':'192.0.2.1'},body:f})}
test('origin rejection and missing configuration',async()=>{assert.equal((await worker.fetch(new Request(origin,{method:'POST'}),setup())).status,403);assert.equal((await worker.fetch(req(),{ALLOWED_ORIGINS:origin})).status,503)});
test('validation rejects incomplete and header-injection inputs',async()=>{for(const data of [{email:'bad'},{name:'X\r\nBcc:bad'},{service:'Unknown'},{description:''},{website:'spam'}])assert.equal((await worker.fetch(req(data),setup())).status,400)});
test('signature validation',()=>{assert.equal(imageType(new Uint8Array([137,80,78,71,13,10,26,10])),'image/png');assert.equal(imageType(new TextEncoder().encode('<script>bad</script>')),'')});
test('provider acceptance, replay, rejection, captcha, upload and rate limits',async()=>{const original=global.fetch;let providerCalls=0;global.fetch=async(url,options)=>{if(url.includes('turnstile'))return Response.json({success:true,hostname:'novahomeconstruction.ca',action:'estimate'});providerCalls++;const b=JSON.parse(options.body);assert.equal(b.to[0],'Novaconstruction.home@gmail.com');assert.equal(b.reply_to,'test@example.com');assert(b.subject.includes('Test Person'));assert(b.text.includes('Submitted:'));return Response.json({id:'accepted'})};try{const env=setup();assert.equal((await worker.fetch(req(),env)).status,200);assert.equal((await worker.fetch(req(),env)).status,200);assert.equal(providerCalls,1);assert.equal((await worker.fetch(req({description:'Changed'}),env)).status,409);assert.equal((await worker.fetch(req({},new Blob(['invalid'],{type:'image/png'})),setup())).status,400);for(let i=0;i<6;i++)await worker.fetch(req({email:'bad'}),env);assert.equal((await worker.fetch(req(),env)).status,429);global.fetch=async url=>url.includes('turnstile')?Response.json({success:true,hostname:'novahomeconstruction.ca',action:'estimate'}):Response.json({error:'failed'},{status:500});assert.equal((await worker.fetch(req(),setup())).status,502);global.fetch=async()=>Response.json({success:false});assert.equal((await worker.fetch(req(),setup())).status,400)}finally{global.fetch=original}});
