CREATE TABLE IF NOT EXISTS limits (id TEXT NOT NULL,bucket INTEGER NOT NULL,n INTEGER NOT NULL,PRIMARY KEY(id,bucket));
CREATE TABLE IF NOT EXISTS requests (id TEXT PRIMARY KEY,hash TEXT NOT NULL,created INTEGER NOT NULL,sent INTEGER NOT NULL DEFAULT 0);
