const SERVICES=['Full Home Renovation','Kitchen Renovation','Bathroom Renovation','Basement Development','Flooring Installation','Stairs and Railings','Deck Construction','Fence Installation','Interior and Exterior Painting','Drywall and Framing','Doors and Windows','Exterior Siding','Other Construction Services'];
const MAX=7*1024*1024;
export function imageType(b){if(b[0]===255&&b[1]===216&&b[2]===255)return 'image/jpeg';if([137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))return 'image/png';if(new TextDecoder().decode(b.slice(0,4))==='RIFF'&&new TextDecoder().decode(b.slice(8,12))==='WEBP')return 'image/webp';return ''}
async function digest(s){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function bounded(request){const reader=request.body.getReader();let size=0,parts=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>MAX){await reader.cancel();throw Error('large')}parts.push(value)}return new Response(new Blob(parts),{headers:{'Content-Type':request.headers.get('content-type')}}).formData()}
export default {async fetch(request,env){
const origin=request.headers.get('Origin'),allowed=(env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim());const headers={'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'",'Vary':'Origin'};
const reply=(status,data)=>new Response(JSON.stringify(data),{status,headers});
if(!origin||!allowed.includes(origin))return reply(403,{error:'origin'});headers['Access-Control-Allow-Origin']=origin;
if(request.method==='OPTIONS'){headers['Access-Control-Allow-Methods']='POST';headers['Access-Control-Allow-Headers']='Content-Type';return new Response(null,{status:204,headers})}
if(request.method!=='POST')return reply(405,{error:'method'});
if(!env.DB||!env.RESEND_API_KEY||!env.TURNSTILE_SECRET||!env.RATE_SECRET||!env.FROM_EMAIL)return reply(503,{error:'configuration'});
try{
const ip=request.headers.get('CF-Connecting-IP');if(!ip)return reply(400,{error:'request'});
const hkey=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.RATE_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const ipHash=[...new Uint8Array(await crypto.subtle.sign('HMAC',hkey,new TextEncoder().encode(ip)))].map(n=>n.toString(16).padStart(2,'0')).join('');const bucket=Math.floor(Date.now()/3600000);
const count=await env.DB.prepare('INSERT INTO limits (id,bucket,n) VALUES (?,?,1) ON CONFLICT(id,bucket) DO UPDATE SET n=n+1 RETURNING n').bind(ipHash,bucket).first();if(count.n>6)return reply(429,{error:'rate'});
await env.DB.prepare('DELETE FROM limits WHERE bucket < ?').bind(bucket-48).run();await env.DB.prepare('DELETE FROM requests WHERE created < ?').bind(Date.now()-86400000).run();
if(Number(request.headers.get('Content-Length'))>MAX)return reply(413,{error:'size'});
const f=await bounded(request);const v={};for(const k of ['name','email','phone','location','service','description','date','budget','requestId','token','website'])v[k]=typeof f.get(k)==='string'?f.get(k).trim():'';
if(f.get('consent')!=='yes'||v.website||!v.name||v.name.length>200||/[\r\n]/.test(v.name)||!/^\S+@[^\s@]+\.[^\s@]+$/.test(v.email)||v.email.length>200||/[\r\n]/.test(v.email)||v.phone.replace(/\D/g,'').length<7||v.phone.length>200||!SERVICES.includes(v.service)||!v.description||v.description.length>5000||v.location.length>200||v.date.length>100||v.budget.length>100||! /^[0-9a-f-]{36}$/i.test(v.requestId))return reply(400,{error:'validation'});
const check=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:new URLSearchParams({secret:env.TURNSTILE_SECRET,response:v.token,remoteip:ip}),signal:AbortSignal.timeout(10000)});const captcha=await check.json();if(!captcha.success||captcha.action!=='estimate'||!(env.ALLOWED_HOSTNAMES||'').split(',').includes(captcha.hostname))return reply(400,{error:'captcha'});
const photos=f.getAll('photos').filter(x=>typeof x!=='string'&&x.size);let total=0;const attachments=[],photoHashes=[];if(photos.length>5)return reply(400,{error:'photos'});
for(const [i,file] of photos.entries()){total+=file.size;if(file.size>3*1024*1024||total>6*1024*1024)return reply(413,{error:'photos'});const bytes=new Uint8Array(await file.arrayBuffer()),type=imageType(bytes);if(!type||file.type!==type)return reply(400,{error:'photos'});let str='';for(let k=0;k<bytes.length;k+=8192)str+=String.fromCharCode(...bytes.subarray(k,k+8192));attachments.push({filename:`project-${i+1}.${type==='image/jpeg'?'jpg':type.split('/')[1]}`,content:btoa(str)});photoHashes.push(await digest(str))}
const payload=JSON.stringify([v.name,v.email,v.phone,v.location,v.service,v.description,v.date,v.budget,photoHashes]);const hash=await digest(payload);
await env.DB.prepare('INSERT OR IGNORE INTO requests (id,hash,created,sent) VALUES (?,?,?,0)').bind(v.requestId,hash,Date.now()).run();const row=await env.DB.prepare('SELECT hash,created,sent FROM requests WHERE id=?').bind(v.requestId).first();if(row.hash!==hash)return reply(409,{error:'request'});if(row.sent)return reply(200,{accepted:true});
const text=`NEW ESTIMATE REQUEST\nSubmitted: ${new Date(row.created).toISOString()}\nName: ${v.name}\nEmail: ${v.email}\nPhone: ${v.phone}\nLocation: ${v.location||'Not supplied'}\nService: ${v.service}\nPreferred date: ${v.date||'Not supplied'}\nBudget: ${v.budget||'Not supplied'}\n\nProject description:\n${v.description}\n\nPhotos: ${photos.length} attached`;
const result=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`nova-${v.requestId}`},body:JSON.stringify({from:env.FROM_EMAIL,to:['info@novahomeconstruction.ca'],reply_to:v.email,subject:`NEW ESTIMATE REQUEST | NOVA Home Construction | ${v.name}`,text,attachments}),signal:AbortSignal.timeout(15000)});if(!result.ok)return reply(502,{error:'provider'});const data=await result.json();if(!data.id)return reply(502,{error:'provider'});await env.DB.prepare('UPDATE requests SET sent=1 WHERE id=?').bind(v.requestId).run();return reply(200,{accepted:true});
}catch{return reply(502,{error:'request'})}
}};
